{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d7a946c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import getpass\n",
    "import secrets\n",
    "from secretsharing import PlaintextToHexSecretSharer\n",
    "from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes\n",
    "from cryptography.hazmat.primitives.asymmetric import rsa, padding\n",
    "from cryptography.hazmat.primitives import hashes, serialization\n",
    "from cryptography.hazmat.backends import default_backend\n",
    "\n",
    "\n",
    "def get_or_create_rsa_keys():\n",
    "    private_path = \"private_key.pem\"\n",
    "    public_path = \"public_key.pem\"\n",
    "\n",
    "    if not os.path.exists(private_path):\n",
    "        print(\"\\n🔑 Khởi tạo hệ thống khóa RSA lần đầu...\")\n",
    "        password = getpass.getpass(\"Thiết lập mật khẩu bảo vệ file khóa RSA: \")\n",
    "        \n",
    "        private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    "        \n",
    "        # Lưu Private Key\n",
    "        with open(private_path, \"wb\") as f:\n",
    "            f.write(private_key.private_bytes(\n",
    "                encoding=serialization.Encoding.PEM,\n",
    "                format=serialization.PrivateFormat.PKCS8,\n",
    "                encryption_algorithm=serialization.BestAvailableEncryption(password.encode())\n",
    "            ))\n",
    "        \n",
    "        # Lưu Public Key\n",
    "        public_key = private_key.public_key()\n",
    "        with open(public_path, \"wb\") as f:\n",
    "            f.write(public_key.public_bytes(\n",
    "                encoding=serialization.Encoding.PEM,\n",
    "                format=serialization.PublicFormat.SubjectPublicKeyInfo\n",
    "            ))\n",
    "        return private_key, public_key\n",
    "    else:\n",
    "        print (\"LƯU Ý! KHÔNG CHIA SẺ MẬT KHẨU NÀY VỚI AI KHÁC! MẬT KHẨU NÀY CẦN THIẾT ĐỂ TRUY CẬP VÀ SỬ DỤNG KHÓA RSA CỦA BẠN.\")\n",
    "        password = getpass.getpass(\"\\n🔑 Nhập mật khẩu: \")\n",
    "        with open(private_path, \"rb\") as f:\n",
    "            private_key = serialization.load_pem_private_key(f.read(), password=password.encode())\n",
    "        with open(public_path, \"rb\") as f:\n",
    "            public_key = serialization.load_pem_public_key(f.read())\n",
    "        return private_key, public_key\n",
    "\n",
    "# --- MÃ HÓA FILE VỚI AES ---\n",
    "\n",
    "def encrypt_file(file_path):\n",
    "    aes_key = os.urandom(32)  # Khóa 256-bit\n",
    "    iv = os.urandom(16)\n",
    "    \n",
    "    with open(file_path, 'rb') as f:\n",
    "        data = f.read()\n",
    "\n",
    "    cipher = Cipher(algorithms.AES(aes_key), modes.CFB(iv), backend=default_backend())\n",
    "    encryptor = cipher.encryptor()\n",
    "    encrypted_data = encryptor.update(data) + encryptor.finalize()\n",
    "\n",
    "    with open(file_path + \".enc\", 'wb') as f:\n",
    "        f.write(iv + encrypted_data)\n",
    "    \n",
    "    return aes_key\n",
    "\n",
    "# --- CHƯƠNG TRÌNH CHÍNH ---\n",
    "\n",
    "# 1. Khởi tạo khóa RSA\n",
    "try:\n",
    "    priv_key, pub_key = get_or_create_rsa_keys()\n",
    "except Exception as e:\n",
    "    print(f\"❌ Lỗi truy cập khóa: {e}\")\n",
    "    exit()\n",
    "\n",
    "# 2. Mã hóa file và tạo Session Secret\n",
    "target_file = input(\"\\nNhập đường dẫn file cần mã hóa: \")\n",
    "if os.path.exists(target_file):\n",
    "    raw_aes_key = encrypt_file(target_file)\n",
    "    session_salt = secrets.token_hex(4)\n",
    "    # Kết hợp Khóa AES + Salt để tạo bí mật cần chia sẻ\n",
    "    combined_secret = raw_aes_key.hex() + \":\" + session_salt\n",
    "    \n",
    "    # Mã hóa bí mật này bằng RSA Public Key\n",
    "    encrypted_session_secret = pub_key.encrypt(\n",
    "        combined_secret.encode(),\n",
    "        padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None)\n",
    "    )\n",
    "    print(f\"✅ Đã mã hóa file. Session Salt của bạn là: {session_salt}\")\n",
    "else:\n",
    "    print(\"File không tồn tại!\")\n",
    "    exit()\n",
    "\n",
    "# 3. Chia sẻ bí mật (SSS)\n",
    "n = int(input(\"\\nTổng số thành viên phân phát mảnh: \"))\n",
    "k = round(n * 3 / 5)\n",
    "shares = PlaintextToHexSecretSharer.split_secret(encrypted_session_secret.hex(), k, n)\n",
    "\n",
    "print(\"\\n--- CÁC MẢNH BÍ MẬT (HÃY CHIA CHO CÁC THÀNH VIÊN) ---\")\n",
    "for i, s in enumerate(shares, 1):\n",
    "    print(f\"Mảnh {i}: {s}\")\n",
    "\n",
    "# 4. Khôi phục và Giải mã\n",
    "print(f\"\\n--- QUY TRÌNH KHÔI PHỤC (Cần {k} mảnh) ---\")\n",
    "subset = [input(f\"Nhập mảnh thứ {i+1}: \") for i in range(k)]\n",
    "\n",
    "try:\n",
    "    recovered_hex = PlaintextToHexSecretSharer.recover_secret(subset)\n",
    "    # Giải mã bằng RSA Private Key\n",
    "    decrypted_combined = priv_key.decrypt(\n",
    "        bytes.fromhex(recovered_hex),\n",
    "        padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None)\n",
    "    ).decode()\n",
    "    \n",
    "    recovered_aes_key_hex, recovered_salt = decrypted_combined.split(\":\")\n",
    "    \n",
    "    print(f\"\\n🔓 Khôi phục thành công!\")\n",
    "    print(f\"Khóa AES: {recovered_aes_key_hex}\")\n",
    "    print(f\"Salt xác nhận: {recovered_salt}\")\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"❌ Khôi phục thất bại. Mảnh sai hoặc mật khẩu RSA sai! ({e})\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "502a921c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, secrets\n",
    "from flask import Flask, request, send_file, render_template_string\n",
    "from secretsharing import PlaintextToHexSecretSharer\n",
    "from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes\n",
    "from cryptography.hazmat.primitives.asymmetric import rsa, padding\n",
    "from cryptography.hazmat.primitives import hashes, serialization\n",
    "from cryptography.hazmat.backends import default_backend\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# --- RSA Key Management ---\n",
    "def get_or_create_rsa_keys(password: str):\n",
    "    private_path = \"private_key.pem\"\n",
    "    public_path = \"public_key.pem\"\n",
    "\n",
    "    if not os.path.exists(private_path):\n",
    "        private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    "        # Save private key (encrypted with password)\n",
    "        with open(private_path, \"wb\") as f:\n",
    "            f.write(private_key.private_bytes(\n",
    "                encoding=serialization.Encoding.PEM,\n",
    "                format=serialization.PrivateFormat.PKCS8,\n",
    "                encryption_algorithm=serialization.BestAvailableEncryption(password.encode())\n",
    "            ))\n",
    "        # Save public key\n",
    "        public_key = private_key.public_key()\n",
    "        with open(public_path, \"wb\") as f:\n",
    "            f.write(public_key.public_bytes(\n",
    "                encoding=serialization.Encoding.PEM,\n",
    "                format=serialization.PublicFormat.SubjectPublicKeyInfo\n",
    "            ))\n",
    "        return private_key, public_key\n",
    "    else:\n",
    "        with open(private_path, \"rb\") as f:\n",
    "            private_key = serialization.load_pem_private_key(f.read(), password=password.encode())\n",
    "        with open(public_path, \"rb\") as f:\n",
    "            public_key = serialization.load_pem_public_key(f.read())\n",
    "        return private_key, public_key\n",
    "\n",
    "# --- AES File Encryption ---\n",
    "def encrypt_file(file_path):\n",
    "    aes_key = os.urandom(32)  # 256-bit key\n",
    "    iv = os.urandom(16)\n",
    "    with open(file_path, 'rb') as f:\n",
    "        data = f.read()\n",
    "    cipher = Cipher(algorithms.AES(aes_key), modes.CFB(iv), backend=default_backend())\n",
    "    encryptor = cipher.encryptor()\n",
    "    encrypted_data = encryptor.update(data) + encryptor.finalize()\n",
    "    enc_path = file_path + \".enc\"\n",
    "    with open(enc_path, 'wb') as f:\n",
    "        f.write(iv + encrypted_data)\n",
    "    return aes_key, enc_path\n",
    "\n",
    "# --- Flask Routes ---\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return render_template_string('''\n",
    "    <h2>Upload file để mã hóa</h2>\n",
    "    <form method=\"post\" action=\"/upload\" enctype=\"multipart/form-data\">\n",
    "        <input type=\"file\" name=\"file\"><br><br>\n",
    "        <input type=\"password\" name=\"rsa_pass\" placeholder=\"Mật khẩu RSA\"><br><br>\n",
    "        <input type=\"submit\" value=\"Mã hóa\">\n",
    "    </form>\n",
    "    ''')\n",
    "\n",
    "@app.route('/upload', methods=['POST'])\n",
    "def upload_file():\n",
    "    uploaded_file = request.files['file']\n",
    "    rsa_pass = request.form['rsa_pass']\n",
    "    if uploaded_file.filename != '':\n",
    "        os.makedirs(\"uploads\", exist_ok=True)\n",
    "        file_path = os.path.join(\"uploads\", uploaded_file.filename)\n",
    "        uploaded_file.save(file_path)\n",
    "\n",
    "        # RSA keys\n",
    "        priv_key, pub_key = get_or_create_rsa_keys(rsa_pass)\n",
    "\n",
    "        # Encrypt file with AES\n",
    "        raw_aes_key, enc_path = encrypt_file(file_path)\n",
    "        session_salt = secrets.token_hex(4)\n",
    "        combined_secret = raw_aes_key.hex() + \":\" + session_salt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7efc7b4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, secrets\n",
    "from flask import Flask, request, send_file, render_template_string\n",
    "from secretsharing import PlaintextToHexSecretSharer\n",
    "from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes\n",
    "from cryptography.hazmat.primitives.asymmetric import rsa, padding\n",
    "from cryptography.hazmat.primitives import hashes, serialization\n",
    "from cryptography.hazmat.backends import default_backend\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# --- RSA Key Management ---\n",
    "def get_or_create_rsa_keys(password: str):\n",
    "    private_path = \"private_key.pem\"\n",
    "    public_path = \"public_key.pem\"\n",
    "\n",
    "    if not os.path.exists(private_path):\n",
    "        private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)\n",
    "        # Save private key (encrypted with password)\n",
    "        with open(private_path, \"wb\") as f:\n",
    "            f.write(private_key.private_bytes(\n",
    "                encoding=serialization.Encoding.PEM,\n",
    "                format=serialization.PrivateFormat.PKCS8,\n",
    "                encryption_algorithm=serialization.BestAvailableEncryption(password.encode())\n",
    "            ))\n",
    "        # Save public key\n",
    "        public_key = private_key.public_key()\n",
    "        with open(public_path, \"wb\") as f:\n",
    "            f.write(public_key.public_bytes(\n",
    "                encoding=serialization.Encoding.PEM,\n",
    "                format=serialization.PublicFormat.SubjectPublicKeyInfo\n",
    "            ))\n",
    "        return private_key, public_key\n",
    "    else:\n",
    "        with open(private_path, \"rb\") as f:\n",
    "            private_key = serialization.load_pem_private_key(f.read(), password=password.encode())\n",
    "        with open(public_path, \"rb\") as f:\n",
    "            public_key = serialization.load_pem_public_key(f.read())\n",
    "        return private_key, public_key\n",
    "\n",
    "# --- AES File Encryption ---\n",
    "def encrypt_file(file_path):\n",
    "    aes_key = os.urandom(32)  # 256-bit key\n",
    "    iv = os.urandom(16)\n",
    "    with open(file_path, 'rb') as f:\n",
    "        data = f.read()\n",
    "    cipher = Cipher(algorithms.AES(aes_key), modes.CFB(iv), backend=default_backend())\n",
    "    encryptor = cipher.encryptor()\n",
    "    encrypted_data = encryptor.update(data) + encryptor.finalize()\n",
    "    enc_path = file_path + \".enc\"\n",
    "    with open(enc_path, 'wb') as f:\n",
    "        f.write(iv + encrypted_data)\n",
    "    return aes_key, enc_path\n",
    "\n",
    "# --- Flask Routes ---\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return render_template_string('''\n",
    "    <h2>Upload file để mã hóa</h2>\n",
    "    <form method=\"post\" action=\"/upload\" enctype=\"multipart/form-data\">\n",
    "        <input type=\"file\" name=\"file\"><br><br>\n",
    "        <input type=\"password\" name=\"rsa_pass\" placeholder=\"Mật khẩu RSA\"><br><br>\n",
    "        <input type=\"submit\" value=\"Mã hóa\">\n",
    "    </form>\n",
    "    ''')\n",
    "\n",
    "@app.route('/upload', methods=['POST'])\n",
    "def upload_file():\n",
    "    uploaded_file = request.files['file']\n",
    "    rsa_pass = request.form['rsa_pass']\n",
    "    if uploaded_file.filename != '':\n",
    "        os.makedirs(\"uploads\", exist_ok=True)\n",
    "        file_path = os.path.join(\"uploads\", uploaded_file.filename)\n",
    "        uploaded_file.save(file_path)\n",
    "\n",
    "        # RSA keys\n",
    "        priv_key, pub_key = get_or_create_rsa_keys(rsa_pass)\n",
    "\n",
    "        # Encrypt file with AES\n",
    "        raw_aes_key, enc_path = encrypt_file(file_path)\n",
    "        session_salt = secrets.token_hex(4)\n",
    "        combined_secret = raw_aes_key.hex() + \":\" + session_salt\n",
    "\n",
    "        # Encrypt combined secret with RSA\n",
    "        encrypted_session_secret = pub_key.encrypt(\n",
    "            combined_secret.encode(),\n",
    "            padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()),\n",
    "                         algorithm=hashes.SHA256(), label=None)\n",
    "        )\n",
    "\n",
    "        # Split secret into shares\n",
    "        n, k = 5, 3  # ví dụ: 5 thành viên, cần 3 mảnh\n",
    "        shares = PlaintextToHexSecretSharer.split_secret(encrypted_session_secret.hex(), k, n)\n",
    "\n",
    "        # Hiển thị shares + cho tải file .enc\n",
    "        html = \"<h3>File đã mã hóa xong!</h3>\"\n",
    "        html += f\"<p>Salt phiên: {session_salt}</p>\"\n",
    "        html += \"<p>Các mảnh bí mật:</p><ul>\"\n",
    "        for i, s in enumerate(shares, 1):\n",
    "            html += f\"<li>Mảnh {i}: {s}</li>\"\n",
    "        html += \"</ul>\"\n",
    "        html += f'<a href=\"/download/{os.path.basename(enc_path)}\">Tải file mã hóa</a>'\n",
    "        return html\n",
    "    return \"Không có file nào được tải lên!\"\n",
    "\n",
    "@app.route('/download/<filename>')\n",
    "def download_file(filename):\n",
    "    return send_file(os.path.join(\"uploads\", filename), as_attachment=True)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
